[package]
name = "azalea-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
azalea = {path = "../azalea-chunk-event/azalea/"}
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "0.19.3"
pollster = "0.3.0"
bytemuck = { version = "1.15.0", features = ["derive"] }
image = "0.24"
thiserror = "1.0.59"
